# Generated by Django 4.2 on 2023-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
