# Generated by Django 4.2 on 2023-10-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_auth", "0002_alter_profile_address_alter_profile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
