# Generated by Django 4.2 on 2023-10-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_auth", "0003_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
