# Generated by Django 4.2 on 2023-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_auth", "0005_alter_profile_birth_date_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
