version: '3.8'
services:
  db:
    image: postgres:14
    container_name: rest_db
    user: postgres
    volumes:
      - pg_store:/var/lib/postgresql/data:rw
    env_file:
      - api_design/.env
    ports:
      - '5432:5432'
    networks:
      - api_network
    restart: always

  frontend:
    image: rest_frontend
    build:
      context: rest_frontend/
    ports:
      - '3000-3005:3000'
    depends_on:
      - db
      - backend
    env_file:
      - api_design/.env
    networks:
      - api_network
    restart: always

  backend:
    container_name: rest_backend
    image: rest_backend
    build:
      context: api_design/
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - api_design/.env
    networks:
      - api_network
    restart: always

networks:
  api_network:
    driver: bridge
volumes:
  pg_store: