# Generated by Django 4.2 on 2023-10-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_product",
                to="api_db.products",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_session",
                to="api_db.shoppingsession",
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_order",
                to="api_db.orderdetails",
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_product",
                to="api_db.products",
            ),
        ),
    ]
