# Generated by Django 4.2 on 2023-11-01 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_db", "0003_alter_productcategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-id"], "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={"ordering": ["-id"], "verbose_name_plural": "Discounts"},
        ),
        migrations.AlterModelOptions(
            name="orderdetails",
            options={"ordering": ["-id"], "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitems",
            options={"ordering": ["-id"], "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="paymentdetails",
            options={"ordering": ["-id"], "verbose_name_plural": "Payments"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["-id"], "verbose_name_plural": "Category"},
        ),
        migrations.AlterModelOptions(
            name="productinventory",
            options={"ordering": ["-id"], "verbose_name_plural": "Inventory"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"ordering": ["-id"], "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="shoppingsession",
            options={"ordering": ["-id"], "verbose_name_plural": "Sessions"},
        ),
        migrations.AlterModelOptions(
            name="useraddresses",
            options={"ordering": ["-id"], "verbose_name_plural": "User Address"},
        ),
        migrations.AlterModelOptions(
            name="userpayment",
            options={"ordering": ["-id"], "verbose_name_plural": "User Payments"},
        ),
    ]
